database:
  backup_enabled: true
  backup_interval_hours: 24
  faiss_index_path: database/faiss_index
  sqlite_path: database/ballistics.db
gui:
  auto_save: true
  language: es
  theme: default
  window_height: 800
  window_width: 1200
image_processing:
  max_image_size: 2048
  orb_features: 5000
  roi_detection_method: simple
  sift_features: 1000
  supported_formats:
  - .jpg
  - .jpeg
  - .png
  - .tif
  - .tiff
  - .bmp
logging:
  backup_count: 5
  console_output: true
  file_path: logs/ballistics.log
  level: INFO
  max_file_size: 10MB
matching:
  distance_threshold: 0.75
  matcher_type: BF
  max_results: 5
  min_matches: 10
  similarity_threshold: 0.3
deep_learning:
  enabled: false
  device: cpu
  batch_size: 16
  learning_rate: 0.001
  epochs: 100
  dropout_rate: 0.5
  models:
    cnn:
      enabled: false
      input_size: 224
      num_classes: 10
      hidden_layers: [512, 256, 128]
    autoencoder:
      enabled: false
      input_size: 224
      latent_dim: 128
      hidden_layers: [512, 256]
    siamese:
      enabled: false
      input_size: 224
      embedding_dim: 128
      margin: 1.0
    unet:
      enabled: false
      input_channels: 3
      output_channels: 1
      base_filters: 64
    resnet:
      enabled: false
      input_size: 224
      num_classes: 10
      pretrained: false
