_metadata:
  created: '2025-10-05T06:03:23.909951'
  environment: development
  project_root: /home/marco/SIGeC-Balistica
  version: 1.0.0
database:
  backup_enabled: true
  backup_interval_hours: 24
  backup_path: database/backups
  backup_retention_days: 30
  connection_pool_size: 10
  db_path: database
  enable_wal_mode: true
  faiss_index_path: database/faiss_index
  query_timeout: 30
  sqlite_path: database/ballistics.db
deep_learning:
  autoencoder_config:
    enabled: false
    hidden_layers:
    - 512
    - 256
    input_size: 224
    latent_dim: 128
  batch_size: 16
  checkpoints_path: deep_learning/checkpoints
  cnn_config:
    enabled: false
    hidden_layers:
    - 512
    - 256
    - 128
    input_size: 224
    num_classes: 10
  device: cpu
  dropout_rate: 0.5
  enabled: false
  epochs: 100
  learning_rate: 0.001
  models_path: deep_learning/models
  siamese_config:
    embedding_dim: 128
    enabled: false
    input_size: 224
    margin: 1.0
  tensorboard_path: deep_learning/logs
gui:
  auto_save: true
  auto_save_interval: 300
  default_image_quality: 95
  enable_animations: true
  font_family: Arial
  font_size: 10
  image_zoom_step: 0.1
  language: es
  max_zoom_level: 10.0
  min_window_height: 600
  min_window_width: 800
  min_zoom_level: 0.1
  panel_transparency: 0.9
  remember_window_state: true
  show_metadata_panel: true
  show_progress_panel: true
  show_statistics_panel: true
  show_tooltips: true
  theme: default
  window_height: 800
  window_width: 1200
image_processing:
  cache_path: cache/images
  clahe_clip_limit: 2.0
  clahe_grid_size: 8
  enable_illumination_correction: true
  enable_parallel_processing: true
  enhance_breech_marks: false
  enhance_firing_pin: false
  enhance_striations: false
  gaussian_kernel_size: 5
  maintain_aspect_ratio: true
  max_image_size: 2048
  max_workers: 4
  memory_limit_mb: 1024
  min_image_size: 64
  orb_features: 5000
  output_path: output
  resize_images: true
  roi_detection_method: simple
  sift_features: 1000
  supported_formats:
  - .jpg
  - .jpeg
  - .png
  - .tif
  - .tiff
  - .bmp
  temp_path: temp
logging:
  backup_count: 5
  console_output: true
  date_format: '%Y-%m-%d %H:%M:%S'
  enable_compression: true
  enable_rotation: true
  file_path: logs/ballistics.log
  format_string: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  log_memory_usage: false
  log_path: logs
  log_performance_metrics: true
  max_file_size: 10MB
  module_levels: {}
matching:
  algorithm: !!python/object/apply:matching.unified_matcher.AlgorithmType
  - ORB
  batch_size: 100
  cache_descriptors: true
  distance_threshold: 0.75
  enable_breech_face_analysis: true
  enable_cross_check: true
  enable_firing_pin_analysis: true
  enable_geometric_verification: true
  enable_gpu_acceleration: false
  enable_impression_analysis: true
  enable_parallel_matching: true
  enable_ratio_test: true
  enable_striation_analysis: true
  enable_symmetry_test: false
  gpu_device_id: 0
  gpu_fallback_to_cpu: true
  level: !!python/object/apply:matching.unified_matcher.MatchingLevel
  - standard
  matcher_type: BF
  max_features: 1000
  max_iterations: 2000
  max_results: 5
  min_matches: 10
  ransac_confidence: 0.99
  ransac_threshold: 5.0
  similarity_threshold: 0.3
nist:
  enable_afte_standards: true
  enable_chain_of_custody: true
  enable_nist_compliance: true
  enable_peer_review: true
  enable_quality_weighting: true
  generate_compliance_reports: true
  include_metadata: true
  min_quality_score: 0.7
  quality_threshold: 0.8
  report_format: json
  require_examiner_certification: false
